[package]
name = "mcp2221"
description = "MCP2221 I2C/GPIO driver"
repository = "https://github.com/google/mcp2221-rs"
version = "0.1.1"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
embedded-hal = "0.2.6"
hidapi = "2.4.1"
